### ISSUE TITLE
Core Piny

### ISSUE THREAD

**Issue by Audio-Video-Tech** [stefslon/cec-arduino#1]
Hii

Have an Error:

Arduino: 1.6.1 (Windows 7), Board: "Arduino Uno"

In file included from Serial.h:4:0,

```
             from CECWire.h:4,

             from CEC.h:4,

             from CEC.cpp:1:
```

Common.h:26:23: fatal error: core_pins.h: No such file or directory

 #include <core_pins.h>

```
                   ^
```

compilation terminated.

Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by robot256** [comment]
The code does not seem to be structured in a way that will compile in Arduino 1.6.4.  It may be designed for a different development environment, or a non-Uno-based platform.  Unless stefslon decides to maintain it, someone will have to fork and rebuild it into a proper Arduino library.

**Comment by stefslon** [comment]
I am still working on this... I switched to the newest Arduino software and I've been changing code to be able to compile and fit it on ATTINY85. It's not finished, but it compiles and interacts with CEC. Since someone besides me is looking for this code I will commit what I have in the next few days.

**Comment by robot256** [comment]
That's great news! I am working (slowly) on a home automation system for my
media console. Tiny code will be perfect, since there's not a lot of space
left in my Uno after the Ethernet and webserver.
Thanks!
Tom

**Comment by stefslon** [comment]
I've committed what I have. Hope it works for you!
